kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: sentinel
  namespace: sentinel
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "sentinel:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: ./Dockerfile
      from:
        kind: ImageStreamTag
        name: "syslog-ng-ose:latest"
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/michaelshire/sentinel.git"
  runPolicy: Serial
