kind: Deployment
apiVersion: apps/v1
metadata:
  name: sentinel
  namespace: sentinel
  labels:
    app: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: sentinel
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: sentinel
    spec:
      volumes:
        - name: sentinel-workspace
          secret:
            secretName: sentinel-workspace
      containers:
        - name: sentinelimage
          image: 'image-registry.openshift-image-registry.svc:5000/sentinel/sentinel:latest'
          resources: {}
          volumeMounts:
            - name: sentinel-workspace
              mountPath: /var/run/secrets/kubernetes.io/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
