kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: sentinel
  namespace: sentinel
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: 'image-registry.openshift-image-registry.svc:5000/sealed-secrets/sentinel'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: syslog-ng
  namespace: sentinel
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: 'balabit/syslog-ng'
      from:
        kind: DockerImage
        name: 'balabit/syslog-ng:latest'
      importPolicy: {}
      referencePolicy:
        type: Source
